backend:
  name: git-gateway
  branch: master

media_folder: "images"

collections:
  - name: "blog"
    label: "Blog"
    label_singular: "Blog post"
    folder: "content/post"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Thumbnail Image", name: "thumbnailImage", widget: "image", required: false, hint: "This is not necessary."}
      - {label: "Post Body", name: "body", widget: "markdown", default: "## Heading"}
      - label: "Categories"
        label_singular: "Category"
        name: "categories"
        widget: "list"
        #field: {label: "Category", name: "categories", widget: "list"}
        min: 2
        max: 2
        summary: "{{fields.categories}}"
        collapsed: true
        #allow_add: true
        hint: "Enter a category and a subcategory. See other posts for ideas"
      - label: "Tags"
        label_singular: "Tag"
        name: "tags"
        widget: "list"
        #field: {label: "Tag", name: "tags", widget: "list"}
        summary: "{{fields.tags}}"
        collapsed: true
        #allow_add: true
        min: 1
        hint: "Try to reuse tags from other posts, if possible"
      - label: "Keywords"
        label_singular: "Keyword"
        name: "keywords"
        widget: "list"
        #field: {label: "Keyword", name: "keywords", widget: "list"}
        collapsed: true
        #allow_add: true
        summary: "{{fields.keywords}}"
        hint: "Just use the tags list as your keywords too."
      - label: "Comments"
        name: "comments"
        widget: "hidden"
        default: false
