backend:
  name: git-gateway
  branch: master

media_folder: "images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/post"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Thumbnail Image", name: "thumbnailImage", widget: "image", required: false, hint: "This is not necessary."}
      - {label: "Post Body", name: "body", widget: "markdown", default: "## Heading"}
      - label: "Categories, Tags and Keywords"
        name: "categories_tags"
        widget: "object"
        collapsed: true
        summary: "Pick and add Categories, Tags and Keywords"
        fields:
          - label: "Categories"
            name: "categories"
            widget: "string"
            default: ['cat','subcat']
            hint: "Enter a category and a subcategory. See other posts for ideas"
          - label: "Tags"
            name: "tags"
            widget: "string"
            default: ['tag1','tag2']
            hint: "Try to reuse tags from other posts, if possible"
          - label: "Keywords"
            name: "keywords"
            widget: "string"
            default: ['kwd1','kwd2'
            hint: "Just use the tags list as your keywords too."